obj/hf_interrupts.o: src/hf_interrupts.c bsp/drivers/plic/plic_driver.h \
 bsp/env/freedom-e300-hifive1/platform.h bsp/include/sifive/const.h \
 bsp/include/sifive/devices/aon.h bsp/include/sifive/devices/clint.h \
 bsp/include/sifive/devices/gpio.h bsp/include/sifive/devices/otp.h \
 bsp/include/sifive/devices/plic.h bsp/include/sifive/devices/prci.h \
 bsp/include/sifive/devices/pwm.h bsp/include/sifive/devices/spi.h \
 bsp/include/sifive/devices/uart.h bsp/env/hifive1.h src/hf_interrupts.h \
 bsp/env/encoding.h
obj/skeleton.o: src/skeleton.c bsp/env/freedom-e300-hifive1/platform.h \
 bsp/include/sifive/const.h bsp/include/sifive/devices/aon.h \
 bsp/include/sifive/devices/clint.h bsp/include/sifive/devices/gpio.h \
 bsp/include/sifive/devices/otp.h bsp/include/sifive/devices/plic.h \
 bsp/include/sifive/devices/prci.h bsp/include/sifive/devices/pwm.h \
 bsp/include/sifive/devices/spi.h bsp/include/sifive/devices/uart.h \
 bsp/env/hifive1.h src/hf_interrupts.h bsp/env/encoding.h
